name: chatchit
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1
  firebase_core: ^2.31.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.4
  cached_network_image: ^3.3.1
  image_picker: ^1.1.1
  firebase_storage: ^11.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "icon_launcher"
  ios: true
  image_path: "assets/img/chat.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/img/
