// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPJRyfwSKUstBVItxT8rs-ElB07Y9_4HQ',
    appId: '1:595201228387:android:cdf3abddfbe7a94c1fc256',
    messagingSenderId: '595201228387',
    projectId: 'chat-chit-c8a49',
    storageBucket: 'chat-chit-c8a49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKTlbZ5ylo9BSoh1H3si01XN1E5237rAk',
    appId: '1:595201228387:ios:b37075ce67fd24681fc256',
    messagingSenderId: '595201228387',
    projectId: 'chat-chit-c8a49',
    storageBucket: 'chat-chit-c8a49.appspot.com',
    androidClientId: '595201228387-i8e1u2fcenv6lfvg6st5r7p88u8tl0bd.apps.googleusercontent.com',
    iosClientId: '595201228387-4gf6nh2ibbolardvnmfm2vlqg2f5bevc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatchit',
  );

}